version: '3'
services:
  front-end-service:
    profiles: ["frontend"]
    env_file: variables.env
    ports:
      - "8080:8080"
      - "9090:9090"
    image: search-the-summits/front-end-service
    build:
      context: ./services/front-end-service
      dockerfile: Dockerfile
    volumes:
      - front-end-volume:/service/var/logs

  elasticsearch:
    profiles: ["frontend", "backend"]
    image: elasticsearch:8.5.2
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - es-volume:/usr/share/elasticsearch/data

  kibana:
    profiles: ["monitoring"]
    image: kibana:8.5.2
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: monitoring.searchthesummits.com
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - kibana-volume:/usr/share/kibana/data

  redis:
    profiles: ["backend"]
    image: redis:7.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    command: redis-server --requirepass redispw

  page-indexing-worker:
    profiles: ["backend"]
    image: search-the-summits/page-indexing-worker
    env_file: variables.env
    environment:
      - JAVA_OPTS=-Xmx=600m
    ports:
      - "8081:8080"
      - "9091:9090"
      - "8849:8849"
    build:
      context: ./services/page-indexing-worker
      dockerfile: Dockerfile
    volumes:
      - page-indexing-volume:/service/var/logs

  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus
    ports:
      - "9092:9090"
    build:
      context: ./services/prometheus
      dockerfile: Dockerfile

  grafana:
    profiles: ["monitoring"]
    image: grafana/grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - "3000:3000"


volumes:
  es-volume:
    external: true
  redis-volume:
    external: false
  grafana-volume:
    external: false
  kibana-volume:
    external: false
  page-indexing-volume:
    external: false
  front-end-volume:
    external: false


