global:
  scrape_interval: 1m
  evaluation_interval: 1m


scrape_configs:
  - job_name: 'front-end-service'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'front-end-service:9090' ]

  - job_name: 'page-indexing-worker'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'page-indexing-worker:9090' ]